apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
  - name: app-container
    image: nginx:latest
    volumeMounts:
    - mountPath: /app/logs
      name: app-logs-volume
  volumes:
  - name: app-logs-volume
    persistentVolumeClaim:
      claimName: app-logs-pvc

