version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: ivolve_db
    environment:
      MYSQL_ROOT_PASSWORD: omar
      MYSQL_DATABASE: ivolve
      MYSQL_USER: omar
      MYSQL_PASSWORD: omar
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: ivolve_app
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: omar
      DB_PASSWORD: omar
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./:/app   
    restart: unless-stopped


volumes:
  db_data:
