apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: ivolve
spec:
  serviceName: "mysql"           # اسم الـ headless service
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      # toleration عشان يشتغل على نود مهَتّه بالـ taint workload=worker:NoSchedule
      tolerations:
      - key: "workload"
        operator: "Equal"
        value: "worker"
        effect: "NoSchedule"

      containers:
      - name: mysql
        image: mysql:8.0            # أو أي إصدار تفضله
        ports:
        - containerPort: 3306
          name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          value: ivolve
        - name: MYSQL_USER
          value: ivolveuser
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: DB_PASSWORD
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        # readiness probe (يتأكد إن MySQL جاهز)
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - mysqladmin ping -uroot -p"$MYSQL_ROOT_PASSWORD"
          initialDelaySeconds: 10
          periodSeconds: 10

  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
      # يمكنك تحديد storageClassName لو عندك واحد محدد
      # storageClassName: standard

