apiVersion: v1
kind: Pod
metadata:
  name: with-toleration
spec:
  tolerations:
  - key: "workload"
    operator: "Equal"
    value: "worker"
    effect: "NoSchedule"
  containers:
  - name: busybox
    image: busybox
    command: ["sh", "-c", "sleep 3600"]
