pipeline {
    agent any

    environment {
        DOCKER_HUB_USER = 'omarghalyy'
        IMAGE_NAME = 'jenkins_app'
        IMAGE_TAG = "v${BUILD_NUMBER}"
        DEPLOY_FILE = '/home/omar/DevOps-Tools/CI-CD/Lab30/deployment.yaml'
    }

    stages {

        stage('Clone Repository') {
            steps {
                git 'https://github.com/Ibrahim-Adel15/Jenkins_App.git'
            }
        }

        stage('Run Unit Tests') {
            steps {
                sh 'mvn test'
            }
        }

        stage('Build Application') {
            steps {
                sh 'mvn package -DskipTests'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $DOCKER_HUB_USER/$IMAGE_NAME:$IMAGE_TAG .'
            }
        }

        stage('Push to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-cred', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
                    sh '''
                        echo "$PASS" | docker login -u "$USER" --password-stdin
                        docker push $DOCKER_HUB_USER/$IMAGE_NAME:$IMAGE_TAG
                    '''
                }
            }
        }

        stage('Remove Local Image') {
            steps {
                sh 'docker rmi $DOCKER_HUB_USER/$IMAGE_NAME:$IMAGE_TAG || true'
            }
        }

        stage('Update Deployment File') {
            steps {
                sh '''
                sed -i "s|image: .*|image: $DOCKER_HUB_USER/$IMAGE_NAME:$IMAGE_TAG|" $DEPLOY_FILE
                '''
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                sh 'kubectl apply -f $DEPLOY_FILE'
            }
        }
    }

    post {
        always {
            echo '✅ Pipeline Finished (Always runs)'
        }
        success {
            echo '🎉 Deployment Successful!'
        }
        failure {
            echo '❌ Something went wrong!'
        }
    }
}
