apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-app-deployment
  labels:
    app: jenkins-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-app
  template:
    metadata:
      labels:
        app: jenkins-app
    spec:
      containers:
      - name: jenkins-app
        image: omarghalyy/jenkins_app:v1.0   # Jenkins هيحدث السطر ده تلقائيًا
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-app-service
spec:
  selector:
    app: jenkins-app
  ports:
  - port: 80
    targetPort: 8080
  type: NodePort
